### ISSUE TITLE
docker-compose挂载卷之后 , 更改了挂载卷的所属者 , 不管如何变更权限都会权限错误

### ISSUE THREAD

**Issue by inernoro** [yeasy/docker_practice#367]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Linux
   * [x] CentOS 7
   * [x] Ubuntu 14.04  

### Docker Version

 
* [x] Stable (v18.06) 

### Problem Description

> 此问题适用于任何docker-compose 启动的卷
docker-compose在挂载卷的时候 , 若是此时被人更改了挂载卷的所属者 , 不管如何变更权限 chmod -R 777  或是 chown -R root:root 都会引出权限问题
譬如安装了gitlab-ce 将数据卷挂载为/data目录 , 有一次不小心将/data目录下的所属者设置为 1001:1001 之后 , 不论怎么变更权限, 上面两种方式 , 都会引出权限问题 , 实际上gitlab-ce却是用root账户 , 就算我把所属者变成root 读写改为777 , 一启动就会出问题 

复现方式

```yaml

web: 
   image: 'gitlab/gitlab-ce:latest'
   restart: always
   hostname: 'g.xxx.cn'
   environment:
     GITLAB_OMNIBUS_CONFIG: |
       external_url 'https://g.xxx.cn'
       # Add any other gitlab.rb configuration here, each on its own line
   ports:
     - '80:80'
     - '443:443'
     - '22:22'
   volumes:
     - '/data/gitlab/config:/etc/gitlab'
     - '/data/gitlab/logs:/var/log/gitlab'
     - '/data/gitlab/data:/var/opt/gitlab'
```

> 等待启动之后
> 重试出错的命令
> chown -R 1001:1001 /data
> docker-compose down
> docker-compose up -d
> docker logs <id> 
![11111](https://user-images.githubusercontent.com/9151851/47988402-13f62600-e11d-11e8-92d4-c5b429e947af.png)

> 再次尝试 chmod -R 777 /data
> 权限错误依然存在
