### ISSUE TITLE
wordpress 镜像相关问题

### ISSUE THREAD

**Issue by hans1980775481** [yeasy/docker_practice#414]
wordpress.md  -- 》  下面的

volumes:
  db_data:

的用法是怎样的？？

**Comment by cloudyan** [comment]
```yaml
version: "3.1"

services:

  wordpress:
    image: wordpress:latest
    container_name: wpblog
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: wpdb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - wpdb
    links:
      - wpdb:mysql
    volumes:
      - ~/docker/web/wp-app:/var/www/html

  wpdb:
    # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb

    # mysql:5.7
    # image: mysql:5.7

    # or
    image: mysql:8
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]

    container_name: wpdb
    restart: always
    # ports:
    #   - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: xiaohan
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ~/docker/db/mysql:/var/lib/mysql
```
