### ISSUE TITLE
docker-compose django实战 例子跑不起来

### ISSUE THREAD

**Issue by yytools** [yeasy/docker_practice#479]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Linux
   * [x] CentOS 7

### Docker Version

* [x] Stable (v19.03)

### Problem Description

根据教程提供的例子，会报以下错误：
```
db_1   | Error: Database is uninitialized and superuser password is not specified.
db_1   |        You must specify POSTGRES_PASSWORD to a non-empty value for the
db_1   |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
db_1   | 
db_1   |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
db_1   |        connections without a password. This is *not* recommended.
db_1   | 
db_1   |        See PostgreSQL documentation about "trust":
db_1   |        https://www.postgresql.org/docs/current/auth-trust.html
django_db_1 exited with code 1
```
看错误提示是需要配置`POSTGRES_PASSWORD`或者`POSTGRES_HOST_AUTH_METHOD`

更改后：

django_example/settings.py:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'HOST': 'db',
        'PORT': 5432,
        'PASSWORD': 'postgres',  # 新增密码配置
    }
}
```
docker-compose.yml
```
version: '3'
services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'  # 新增 

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
```

运行正常，建议更新下例子。
